// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// PotReader //
// --------- //

#define PotReader_wrap_target 0
#define PotReader_wrap 6
#define PotReader_pio_version 0

static const uint16_t PotReader_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xe080, //  2: set    pindirs, 0
    0x00c5, //  3: jmp    pin, 5
    0x0043, //  4: jmp    x--, 3
    0xa0c1, //  5: mov    isr, x
    0x8020, //  6: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program PotReader_program = {
    .instructions = PotReader_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = PotReader_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config PotReader_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + PotReader_wrap_target, offset + PotReader_wrap);
    return c;
}
#endif

